name: Isort Formatting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
            requirements-files: "requirements.txt requirements_dev.txt"
